### ISSUE TITLE
거대한 고구마 수확 완료

### ISSUE THREAD

**Issue by OiPKL** [ssafy-12-seoul-8/SWEET_POTATOES#1]
[공통문제1: [PCCE 기출문제] 10번 / 데이터 분석](https://school.programmers.co.kr/learn/courses/30/lessons/250121)
주말에 좀 더 풀어볼게여
일차원 ArrayList <-> 이차원배열 int[ ][ ] 뭔가 여기서 꼬인거같음 . . .
<br/>

![image](https://github.com/user-attachments/assets/6cfaf328-8b81-40cb-8b24-c1294d5d52de)

![image](https://github.com/user-attachments/assets/1e762d05-e4de-492c-a368-762fddad2437)
![image](https://github.com/user-attachments/assets/89b63dc8-116b-4dbe-b61a-40f38e706a70)
![image](https://github.com/user-attachments/assets/3e9b50b0-e7fa-419b-8a3d-4cc8c59eb98e)
![image](https://github.com/user-attachments/assets/b50f2ecb-ff69-44ef-8965-7d866ff638fe)

**Comment by skybory** [comment]
오..내일 점심에 풀어보고 다시 댓글남길게

**Comment by OiPKL** [comment]
![스크린샷 2024-08-03 135208](https://github.com/user-attachments/assets/d5dde399-0ebe-4ba1-af86-7a4c6bf6158e)
![스크린샷 2024-08-03 135218](https://github.com/user-attachments/assets/229fe47e-0c73-43c2-a10f-e77cd88eccf2)


⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⡀⢠⡄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⣰⠞⠞⢶⣄⠀⣠⡾⠚⠶⣦⡴⣯⠰⣗⠀⣴⠟⠳⠞⠏⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⣿⠀⠀⢀⡿⠀⣿⠀⠀⢀⣽⠶⢿⠌⢷⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣠⡦⡦⣤⡤⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠙⠛⠾⣟⠁⠀⠘⠛⠾⠺⠁⠀⠈⠀⠀⠀⠀⠀⠀⢀⣀⣤⣠⣀⡀⠀⠀⠀⠀⠀⠀⢀⣠⣤⡟⠀⠀⣰⡏⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⢀⣠⡿⡶⠞⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣠⡶⢛⠋⠍⡁⡉⡉⠛⢷⣄⠀⠀⠀⠀⠐⠻⠟⠃⠐⢿⡿⠅⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠈⠀⠀⠀⠀⠀⠀⠀⢀⡄⠀⠀⣰⢟⢁⢂⢐⢈⠐⡀⡂⠄⠅⢂⠙⢷⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣽⠂⠀⣸⠏⠄⠂⣾⠞⠞⢾⡔⣰⡦⡧⣦⡈⠸⣗⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢐⡯⠀⢠⣟⠨⠠⠡⢿⣤⣤⣺⠻⣟⣀⢀⣿⠂⡁⣿⠀⠀⠀⢀⣴⠂⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢐⡯⠀⣺⠅⡂⠌⡐⢐⠀⡂⢡⡆⡉⠍⠋⢍⠐⡠⡿⠀⢠⡼⡋⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢐⡯⠀⣿⠐⢐⠐⢐⠐⢐⠠⡑⡓⠠⠨⠈⠄⡂⢸⡏⣰⡛⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⠨⣗⢁⠂⠌⠠⠨⠠⣟⣻⢗⠁⠌⠨⠐⡀⣿⣵⡓⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠺⣵⣗⠐⡈⠌⠨⠠⠁⢝⠟⡐⢈⠌⠨⠐⠠⣿⡗⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⢻⡧⠂⡂⠌⠄⠅⠌⡐⡀⡂⠂⠌⠠⡁⠅⣿⠂⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⢰⡟⢷⣄⠀⠀⠀⠀⠐⣯⠂⡐⡈⡐⡈⡐⡀⠂⠄⡡⠁⠅⡐⠠⢻⡅⠀⠀⢀⣄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⢀⣀⣼⠃⢴⠗⠀⠀⠀⠀⠀⢹⡎⠠⠐⠠⠐⡀⢂⠡⢁⢐⠨⠐⠠⠡⠘⣷⠀⠲⣆⠸⠧⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⡿⣿⠿⠀⠀⠀⠀⠀⠀⠀⠀⠨⣷⠁⠌⡨⠐⢐⠐⡐⡀⡂⠄⠡⢁⠂⡡⠸⣧⠈⠈⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠈⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠸⣧⠡⠐⡈⠄⢂⢐⠠⠐⡈⠌⡀⠢⠐⡈⢾⡂⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢰⡄⢸⡆⠀⠀⠸⣧⠂⡂⠌⡐⢀⢂⠡⠐⡐⠠⠡⠈⠄⢽⡂⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⢿⣀⠛⠅⠀⠀⠙⣧⡐⢐⠐⢐⢀⠂⡡⠠⠡⠈⠌⠨⡾⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠀⠀⠀⠀⠀⠀⠈⠻⣦⡨⡀⡂⡐⠠⠨⠠⢁⣥⠿⠉⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠙⢿⠺⠶⠗⠷⢿⡋⠃⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣿⠀⠀⠀⠀⢸⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣶⠃⠀⠀⠀⠀⣸⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠘⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
