### ISSUE TITLE
(-ing) 가희의 수열놀이..

### ISSUE THREAD

**Issue by OiPKL** [ssafy-12-seoul-8/SWEET_POTATOES#12]
맨 뒤에서부터 조회하는 방법이 리스트에서 뒷 인덱스부터 조회하는걸로 풀어내고 이게 왜 골드지?
했는데 당연하게 시간초과

스택으로 풀어야 한다는데 도저히 모르겠음..

**Comment by Ryuharam** [comment]
동감...나도 시간초과ㅎㅎ

**Comment by OiPKL** [comment]
![image](https://github.com/user-attachments/assets/399b8eef-86a7-45a9-bbfc-faf4642c1409)

정말 좋은 문제인듯
