### ISSUE TITLE
(-ing) N과 M 시간초과

### ISSUE THREAD

**Issue by OiPKL** [ssafy-12-seoul-8/SWEET_POTATOES#13]
N과 M (3) (7) (11)
중복순열 문제들인데 이놈들은 출력할게 너무 많아서 Scanner 로는 안되는거같음....
StringBuffer? 를 배워야 한꺼번에 출력하기(?)로....

**Comment by IjjS** [comment]
내 기억상 이 문제들은 무조건 기본 로깅 말고 StringBuilder/StringBuffer 써야함

**Comment by OiPKL** [comment]
오호..

**Comment by OiPKL** [comment]
String Builder 쓰니까 바로 풀리네
