### ISSUE TITLE
16766. Convention (번역)

### ISSUE THREAD

**Issue by OiPKL** [ssafy-12-seoul-8/SWEET_POTATOES#23]
[Convention I](https://www.acmicpc.net/problem/16766)

문제
농부 존은 자신의 농장에서 새로운 소 모임을 개최하려고 합니다!

전 세계에서 소들이 이 컨벤션에 참석하기 위해 지역 공항에 도착하여 풀을 먹으려고 모이고 있습니다. 구체적으로, 공항에 도착하는 소는 총 N마리이며 (1 ≤ N ≤ 10^5), 소 i는 t_i 시간에 도착합니다 (0 ≤ t_i ≤ 10^9). 농부 존은 소들을 공항에서 운송하기 위해 M대의 버스를 준비했습니다 (1 ≤ M ≤ 10^5). 각 버스는 최대 C마리의 소를 태울 수 있습니다 (1 ≤ C ≤ N). 농부 존은 공항에서 버스와 함께 대기하고 있으며 도착한 소들을 버스에 태워 운송하고 싶습니다. 각 버스는 마지막 소가 도착한 시간에 출발할 수 있습니다. 농부 존은 좋은 주인이 되고 싶기 때문에 도착한 소들이 공항에서 너무 오래 기다리게 하고 싶지 않습니다. 농부 존이 최적으로 버스를 조율했을 때, 도착한 소들 중 어떤 한 마리라도 가장 오래 기다린 시간이 최소화되도록 하려면 그 값은 얼마일까요? 소의 대기 시간은 그녀가 도착한 시간과 그녀가 탑승한 버스가 출발하는 시간 사이의 차이를 의미합니다.

단, M대의 버스가 모든 소를 수용할 수 있는 것이 보장됩니다 (즉, MC ≥ N).

입력
첫 번째 줄에는 세 개의 공백으로 구분된 정수 N, M, C가 주어집니다. 다음 줄에는 N개의 공백으로 구분된 정수들이 주어지며, 각각은 소들이 도착하는 시간을 나타냅니다.

출력
최소화된 최대 대기 시간을 한 줄로 출력하세요.

예제입력1
6 3 2
1 1 10 14 4 3

예제출력1
4

힌트
1번 시간에 도착한 두 마리의 소가 한 대의 버스에 타고, 3번과 4번 시간에 도착한 소는 2번 버스에 타고, 10번과 14번 시간에 도착한 소는 3번 버스에 탈 경우, 소가 기다려야 하는 최대 시간은 4시간입니다(10번 시간에 도착한 소는 10번 시간부터 14번 시간까지 기다립니다).

**Comment by junyoung0619** [comment]
대 완 진

**Comment by Ryuharam** [comment]
대 완 진
